name: "Org Coding Hours v9"
description: "Aggregate coding hours across multiple repositories via git-hours and publish a JSON report."
branding:
  icon: "clock"
  color: "purple"

inputs:
  workdir:
    description: "Path to the repository to analyse"
    required: false
    default: "."
  version:
    description: "git-hours package version to install (npm tag)"
    required: false
    default: "v1.5.0"

outputs:
  report-json:
    description: "Path to generated git-hours.json"
    value: "git-hours.json"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
      with:
        node-version: '20'

    - name: Install git-hours
      shell: bash
      run: |
        set -euo pipefail
        VERSION="${{ inputs.version }}"
        if [[ ! "$VERSION" =~ ^v?\d+(\.\d+){2}$ ]]; then
          echo "Invalid git-hours version: $VERSION" >&2
          exit 1
        fi
        npm install -g git-hours@"$VERSION" || {
          echo "Retrying with nodegit pre-install";
          npm install -g nodegit && npm install -g git-hours@"$VERSION";
        }
        echo "$(npm bin -g)" >> "$GITHUB_PATH"

    - name: Generate coding hours report
      shell: bash
      env:
        WORKDIR: ${{ inputs.workdir }}
      run: |
        set -euo pipefail
        cd "$WORKDIR"
        git-hours > "$GITHUB_WORKSPACE/git-hours.json"
