name: "Org Coding Hours"
description: >
  GitHub Action to compute coding hours across multiple repositories using git-hours (runs in a Docker container).
inputs:
  repos:
    description: Space-separated list of GitHub repositories in owner/name format.
    required: true
  window_start:
    description: Optional start date in YYYY-MM-DD format for the report window.
    required: false
  metrics_branch:
    description: Name of the branch to commit JSON reports to (if provided).
    required: false
    default: metrics
  pages_branch:
    description: Name of the branch to publish the static site to (requires metrics_branch as well).
    required: false
  git_hours_version:
    description: git-hours release tag to use.
    default: v0.1.2
    required: false
outputs:
  aggregated_report:
    description: Path to the aggregated JSON report file
  repo_slug:
    description: Repositories identifier safe for artifact names (slashes and spaces replaced by underscores)
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    REPOS: ${{ inputs.repos }}
    WINDOW_START: ${{ inputs.window_start }}
    METRICS_BRANCH: ${{ inputs.metrics_branch }}
    PAGES_BRANCH: ${{ inputs.pages_branch }}
    GIT_HOURS_VERSION: ${{ inputs.git_hours_version }}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
