runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: '20'

    - name: Validate git-hours version
      shell: bash
      run: |
        set -euo pipefail
        if [[ ! "${{ inputs.version }}" =~ ^v?[0-9]+(\.[0-9]+){2}$ ]]; then
          echo "Invalid git-hours version: ${{ inputs.version }}" >&2
          exit 1
        fi

    - name: Install git-hours
      shell: bash
      run: |
        set -euo pipefail
        npm install -g git-hours@${{ inputs.version }} \
        || { npm install -g nodegit && npm install -g git-hours@${{ inputs.version }}; }
        echo "$(npm bin -g)" >> "$GITHUB_PATH"

    - name: Run git-hours
      shell: bash
      env:
        WORKDIR: ${{ inputs.workdir }}
      run: |
        set -euo pipefail
        cd "$WORKDIR"
        # Default CLI output is JSON → capture it
        git-hours > "$GITHUB_WORKSPACE/git-hours.json"
