runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install git-hours
      shell: bash
      run: |
        npm install -g git-hours@${{ inputs.version }} \
        || { npm install -g nodegit && npm install -g git-hours@${{ inputs.version }}; }
        echo "$(npm bin -g)" >> "$GITHUB_PATH"

    - name: Run git-hours
      shell: bash
      env:
        WORKDIR: ${{ inputs.workdir }}
      run: |
        cd "$WORKDIR"
        # Default CLI output is JSON → capture it
        git-hours > "$GITHUB_WORKSPACE/git-hours.json"
