name: 'Run git-hours'
description: 'Build git-hours from source and output hours‑per‑author JSON'
inputs:
  version:
    description: 'Release tag of Kimmobrunfeldt/git-hours to build from source (e.g. v1.5.0). Use "latest" for the newest.'
    required: false
    default: v1.5.0
  workdir:
    description: 'Path to the repository that should be analysed'
    required: false
    default: ${{ github.workspace }}

runs:
  using: "composite"
  steps:
    # ------------------------------------------------------------------
    # 1. Setup Go and build git-hours
    # ------------------------------------------------------------------
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.x'

    - name: Install git-hours
      shell: bash
      run: |
        go install github.com/Kimmobrunfeldt/git-hours@${{ inputs.version }}
        echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"

    # ------------------------------------------------------------------
    # 2. Generate coding‑hours report
    # ------------------------------------------------------------------
    - name: Run git-hours
      shell: bash
      env:
        WORKDIR: ${{ inputs.workdir }}
      run: |
        git-hours -format json -output git-hours.json "$WORKDIR"
