name: 'Run git-hours'
description: 'Download a pre‑built git-hours binary and output hours‑per‑author JSON'
inputs:
  version:
    description: 'Release tag of lazypic/git-hours to use (e.g. v0.0.6). Use "latest" for the newest.'
    required: false
    default: latest
  workdir:
    description: 'Path to the repository that should be analysed'
    required: false
    default: ${{ github.workspace }}

runs:
  using: "composite"
  steps:
    # ------------------------------------------------------------------
    # 1. Resolve the release tag
    # ------------------------------------------------------------------
    - name: Compute tag
      id: tag
      shell: bash
      run: |
        if [ "${{ inputs.version }}" = "latest" ]; then
          GH_REPO="lazypic/git-hours"
          TAG=$(curl -sfL "https://api.github.com/repos/${GH_REPO}/releases/latest" \
                | grep -m1 '"tag_name"' | cut -d '"' -f4)
        else
          TAG="${{ inputs.version }}"
        fi
        echo "tag=$TAG" >> "$GITHUB_OUTPUT"

    # ------------------------------------------------------------------
    # 2. Download the matching tarball
    # ------------------------------------------------------------------
    - name: Download pre‑built binary
      shell: bash
      env:
        TAG: ${{ steps.tag.outputs.tag }}
      run: |
        set -euo pipefail
        GH_REPO="lazypic/git-hours"
        OS=$(uname -s)
        ARCH=$(uname -m)
        case "${OS}-${ARCH}" in
          Linux-x86_64)  ASSET="git-hours_${TAG#v}_Linux_x86_64.tar.gz" ;;
          Darwin-arm64)  ASSET="git-hours_${TAG#v}_Darwin_arm64.tar.gz" ;;
          Darwin-x86_64) ASSET="git-hours_${TAG#v}_Darwin_x86_64.tar.gz" ;;
          *) echo "Unsupported runner platform ${OS}-${ARCH}" && exit 1 ;;
        esac
        curl -sfL "https://github.com/${GH_REPO}/releases/download/${TAG}/${ASSET}" -o "$ASSET"
        tar -xzf "$ASSET" git-hours
        chmod +x git-hours
        echo "${PWD}" >> $GITHUB_PATH   # <- expose git-hours to later steps

    # ------------------------------------------------------------------
    # 3. Generate coding‑hours report
    # ------------------------------------------------------------------
    - name: Run git-hours
      shell: bash
      env:
        WORKDIR: ${{ inputs.workdir }}
      run: |
        git-hours -format json -output git-hours.json "$WORKDIR"
