name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  docker-action:
    runs-on: ubuntu-latest
    name: Run Docker action on sample repo
    steps:
      - uses: actions/checkout@v4
      - name: Publish CLI
        run: dotnet publish OrgCodingHoursCLI/OrgCodingHoursCLI.csproj -c Release
      - name: Execute action against Hello-World
        uses: ./
        with:
          repos: octocat/Hello-World

  pester-tests:
    runs-on: ubuntu-latest
    name: Run Pester tests for CLI
    steps:
      - uses: actions/checkout@v4
      - name: Publish CLI
        run: dotnet publish OrgCodingHoursCLI/OrgCodingHoursCLI.csproj -c Release
      - name: Run unit tests
        run: dotnet test OrgCodingHoursCLI.Tests/OrgCodingHoursCLI.Tests.csproj
      - name: Install Pester (latest)
        shell: pwsh
        run: |
          Install-Module -Name Pester -RequiredVersion 5.5.0 -Scope CurrentUser -Force
      - name: Run Pester tests
        shell: pwsh
        run: |
          Invoke-Pester

  build_cli:
    runs-on: ubuntu-latest
    name: Build and test CLI
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Extract version
        run: echo "CLI_VERSION=$(grep -oP '(?<=<Version>).*?(?=</Version>)' version.props)" >> $GITHUB_ENV
      - name: Restore
        run: dotnet restore OrgCodingHoursCLI/OrgCodingHoursCLI.csproj
      - name: Build
        run: dotnet build OrgCodingHoursCLI/OrgCodingHoursCLI.csproj -c Release --no-restore
      - name: Run unit tests
        run: dotnet test OrgCodingHoursCLI.Tests/OrgCodingHoursCLI.Tests.csproj
      - name: Install Pester (latest)
        shell: pwsh
        run: |
          Install-Module -Name Pester -RequiredVersion 5.5.0 -Scope CurrentUser -Force
      - name: Run Pester tests
        shell: pwsh
        run: |
          Invoke-Pester
      - name: Pack CLI
        run: dotnet pack OrgCodingHoursCLI/OrgCodingHoursCLI.csproj -c Release -o ./artifacts /p:Version=${CLI_VERSION}
      - name: Build Docker image
        run: docker build --build-arg CLI_VERSION=${CLI_VERSION} -t org-coding-hours-action:${CLI_VERSION} .
      - name: Tag release
        if: github.ref == 'refs/heads/main'
        run: |
          git tag v${CLI_VERSION}
          git push origin v${CLI_VERSION}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: OrgCodingHoursCLI
          path: ./artifacts
