name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker-action:
    runs-on: ubuntu-latest
    name: Run Docker action on sample repo
    steps:
      - uses: actions/checkout@v4
      - name: Execute action against Hello-World
        uses: ./
        with:
          repos: octocat/Hello-World

  pester-tests:
    runs-on: ubuntu-latest
    name: Run Pester tests for CLI
    steps:
      - uses: actions/checkout@v4
      - name: Install Pester (latest)
        shell: pwsh
        run: |
          Install-Module -Name Pester -Scope CurrentUser -Force -SkipPublisherCheck:contentReference[oaicite:3]{index=3}
      - name: Build CLI
        run: dotnet build OrgCodingHoursCLI/OrgCodingHoursCLI.csproj --configuration Release
      - name: Run Pester tests
        shell: pwsh
        run: |
          Invoke-Pester
