name: CI

on:
  push:
    branches: [ develop, main ]
  pull_request:

permissions:
  contents: read
  id-token: write          # future-proof (OIDC uploads, provenance, etc.)

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  coding-hours:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout full history so git‑hours can traverse every commit
      - uses: actions/checkout@v4.1.3
        with:
          fetch-depth: 0

      # 2. Run git‑hours via the new composite action
      - uses: ./.github/actions/git-hours
        id: gh
        with:
          version: v1.5.0              # pinned source build

      # 3. Upload the JSON with a *versioned* name
      - uses: actions/upload-artifact@v4.3.1
        with:
          name: git-hours-${{ github.run_number }}.json
          path: git-hours.json
