name: Org Coding Hours

on:
  workflow_dispatch:

jobs:
  hours:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: LabVIEW-Community-CI-CD/org-coding-hours-action@v9
