name: Org Coding Hours

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  hours:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      - uses: LabVIEW-Community-CI-CD/org-coding-hours-action@0fc5e8b705a8855d2ed08e375eaa345034543be2 # v9
