name: Release

on:
  push:
    tags: [ 'v*.*.*' ]       # semantic version tags
  workflow_dispatch:         # manual execution if desired

permissions:
  contents: write
  id-token: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install pytest
      - run: pytest

  release:
    runs-on: ubuntu-latest
    needs: test
    environment: production    # human approval gate
    steps:
      - uses: actions/checkout@v4.1.3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/git-hours
        with:
          version: latest

      - uses: actions/upload-artifact@v4.3.1
        with:
          name: git-hours-${{ github.run_number }}.json
          path: git-hours.json

      # Create / update the GitHub Release and attach the report
      - name: Create draft GitHub Release
        uses: softprops/action-gh-release@v2.0.5
        with:
          draft: true
          files: git-hours.json
