name: Test and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Verify Python syntax
        run: python -m py_compile scripts/*.py
      - name: Install dependencies
        run: pip install pytest
      - name: Run tests
        run: pytest -q

  publish:
    if: github.event_name == 'release'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            action.yml
            scripts/*.py
            README.md
            LICENSE

