name: Release

on:
  push:
    tags: [ 'v*.*.*' ]       # semantic version tags
  workflow_dispatch:         # manual execution if desired

permissions:
  contents: write
  id-token: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    environment: production    # human approval gate
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/git-hours
        with:
          version: v1.5.0              # pinned source build

      - uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: git-hours-${{ github.run_number }}.json
          path: git-hours.json

      # Create / update the GitHub Release and attach the report
      - name: Create draft GitHub Release
        uses: softprops/action-gh-release@4fabdc8bec0ad32a2eb09fb8fd1d04fd30a75562 # v2.0.5
        with:
          draft: true
          files: git-hours.json
